name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.MACHINE_USER_KEY }}

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.MACHINE_USER_KEY }}

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: npm ci
      - run: npm run lint
